language: go
go:
  - 1.16.x

git:
  depth: 1

branches:
  only:
  - master

install: true

script: 
  - env GO111MODULE=on go test -covermode=atomic -coverprofile=coverage.out $(go list ./...)

after_success:
  - bash <(curl -s https://codecov.io/bash)

