package email

const (
	HEADER_CONTENT_DISPOSITION            = "Content-Disposition"
	HEADER_CONTENT_ID                     = "Content-ID"
	HEADER_CONTENT_TRANSFER_ENCODING      = "Content-Transfer-Encoding"
	HEADER_CONTENT_TYPE                   = "Content-Type"
	HEADER_DATE                           = "Date"
	HEADER_MIME_VERSION                   = "MIME-Version"
	HEADER_MESSAGE_ID                     = "Message-ID"
	HEADER_FROM                           = "From"
	HEADER_TO                             = "To"
	HEADER_CC                             = "Cc"
	HEADER_BCC                            = "Bcc"
	HEADER_REPLY_TO                       = "Reply-To"
	HEADER_IN_REPLY_TO                    = "In-Reply-To"
	HEADER_SUBJECT                        = "Subject"
	HEADER_SENDER                         = "Sender"
	HEADER_MIME_VERSION_10                = "1.0"
	HEADER_CONTENT_DISPOSITION_INLIE      = "inline"
	HEADER_CONTENT_DISPOSITION_ATTACHMENT = "attachment"
	HEADER_LIST_SUBSCRIBE                 = "List-Subscribe"
	HEADER_LIST_POST                      = "List-Post"
	HEADER_LIST_OWNER                     = "List-Owner"
	HEADER_LIST_ID                        = "List-Id"
	HEADER_LIST_ARCHIVE                   = "List-Archive"
	HEADER_LIST_HELP                      = "List-Help"
	HEADER_LIST_UNSUBSCRIBE               = "List-Unsubscribe"
	HEADER_RESENT_FROM                    = "Resent-From"
	HEADER_RESENT_TO                      = "Resent-To"
	HEADER_RESENT_CC                      = "Resent-Cc"
	HEADER_RESENT_DATE                    = "Resent-Date"
	HEADER_RESENT_MESSAGE_ID              = "Resent-Message-ID"
	HEADER_RESENT_SENDER                  = "Resent-Sender"
	HEADER_REFERENCES                     = "References"
	HEADER_DKIM_SIGNATUR                  = "DKIM-Signature"
)
